
export const ADD_UPDATED_ITEM_SUGGESTIONS = 'ADD_UPDATED_ITEM_SUGGESTIONS';
export const REMOVE_ALL_ITEM_SUGGESTIONS = 'REMOVE_ALL_ITEM_SUGGESTIONS';
export const SUGGESTION_POSITION_DOWN = 'SUGGESTION_POSITION_DOWN';
export const SUGGESTION_POSITION_UP = 'SUGGESTION_POSITION_UP';
export const DEFAULT_ACTIVE_INDEX = -1;