export const UPDATE_GROSSAMOUNT = 'UPDATE_GROSSAMOUNT';
export const RESET_INVOICE_TOTAL = 'RESET_INVOICE_TOTAL';
export const UPDATE_INVOICE_INFO = 'UPDATE_INVOICE_INFO';

export const ORDER_SAVE_FAILED_MESSAGE = 'Failed to save order details.';
