export const AUTHENTICATE = 'AUTHENTICATE';
export const AUTHENTICATEION_ERROR = 'AUTHENTICATEION_ERROR';
export const AUTHENTICATEION_RESPONSE_ERROR = 'AUTHENTICATEION_RESPONSE_ERROR';
export const AUTHENTICATEION_SUCCESS = 'AUTHENTICATEION_SUCCESS';
export const USERNAME_PASSWORD_REQUIRED = 'USERNAME_PASSWORD_REQUIRED';
export const USERNAME_REQUIRED = 'USERNAME_REQUIRED';
export const PASSWORD_REQUIRED = 'PASSWORD_REQUIRED';
export const LOGIN_REQUIRED = 'LOGIN_REQUIRED';
export const RELOGIN_REQUIRED = 'RELOGIN_REQUIRED';

export const TYPE_VALIDATION_ERROR = 'TYPE_VALIDATION_ERROR';
export const TYPE_LOGIN_REQUIRED_ERROR = 'TYPE_LOGIN_REQUIRED_ERROR';
export const TYPE_AUTHENTICATION_ERROR = 'TYPE_AUTHENTICATION_ERROR';
export const TYPE_AUTHENTICATION_SUCCESS = 'TYPE_AUTHENTICATION_SUCCESS';